version: "3.9"

services:
  backend:
    build:
      context: ./ai-server
    container_name: house-api

    ports:
      - "8000:8000"

    volumes:
      - ./ai-server:/app

    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: house-react

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: always
